CREATE OR ALTER FUNCTION GiveUserName(@username VARCHAR(50)) RETURNS VARCHAR(50) AS
BEGIN 


DECLARE @STR AS VARCHAR(50) = ''
DECLARE @limit AS INT = CHARINDEX('@',@username) 
SET @STR = SUBSTRING(@username,1,@limit-1)

RETURN @STR

END
GO

